name: crossworduel
description: This is simple crossword game

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.2+2

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  dio: ^5.4.3+1
  get_it: ^7.7.0
  crypto: ^3.0.3
  uuid: ^4.4.0
  date_format: ^2.0.7
  flutter_secure_storage: ^9.2.2
  retrofit: ^4.0.3
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  cached_network_image: ^3.3.0
  flutter_gen: ^5.5.0+1
  flutter_svg: ^2.0.10+1
  sign_in_with_apple: ^6.1.1
  google_sign_in: ^6.1.6
  url_launcher: ^6.3.0
  go_router: ^14.2.0
  confetti: ^0.7.0
  pull_to_refresh: ^2.0.0
  supabase_flutter: ^2.5.7

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.5.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  lint: ^2.2.0
  retrofit_generator: ^8.0.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/icon.png"

# pubspec.yaml
flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    # ICONS
    - assets/icons/
    # IMAGE
    - assets/image/
    # DICT
    - assets/dict/

  fonts:
    # --- opensans--
    - family: sf_heavy
      fonts:
        - asset: assets/fonts/SF-Rounded-Heavy.ttf

    - family: sf_bold
      fonts:
        - asset: assets/fonts/SF-Rounded-Bold.ttf

    - family: sf_medium
      fonts:
        - asset: assets/fonts/SF-Rounded-Medium.ttf
