name: crossworduel
description: This is simple crossword game

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.2+2

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  dio: ^5.4.0
  get_it: ^7.6.4
  crypto: ^3.0.3
  uuid: ^4.2.1
  date_format: ^2.0.7
  flutter_secure_storage: ^9.0.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  cached_network_image: ^3.3.0
  flutter_gen: ^5.3.2
  flutter_svg: ^2.0.9
  sign_in_with_apple: ^5.0.0
  firebase_messaging: ^14.7.6
  google_sign_in: ^6.1.6
  url_launcher: ^6.2.1
  go_router: ^12.1.1
  confetti: ^0.7.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  lint: ^2.2.0
  retrofit_generator: ^8.0.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/icon.png"

# pubspec.yaml
flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    # ICONS
    - assets/icons/
    # IMAGE
    - assets/image/
    # DICT
    - assets/dict/

  fonts:
    # --- opensans--
    - family: sf_heavy
      fonts:
        - asset: assets/fonts/SF-Rounded-Heavy.ttf

    - family: sf_bold
      fonts:
        - asset: assets/fonts/SF-Rounded-Bold.ttf

    - family: sf_medium
      fonts:
        - asset: assets/fonts/SF-Rounded-Medium.ttf
